import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/styles/debug.css";
import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
  title: "Your Name | Software Engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased">
        <main className="flex flex-col lg:flex-row min-h-screen max-w-screen-xl gap-4 mx-auto px-6 py-12 md:px-12 md:py-16 lg:py-0 lg:items-start">
          <Sidebar>
            <Header />
          </Sidebar>
          {children}
        </main>
      </body>
    </html>
  );
}
